/*
 * Renderer Models. The MIT License.
 * Copyright (c) 2022 rlkraft@pnw.edu
 * See LICENSE for details.
*/

/**
   Create a wireframe model of a torus.
<p>
   See <a href="https://en.wikipedia.org/wiki/Torus" target="_top">
                https://en.wikipedia.org/wiki/Torus</a>
<p>
   This torus is the surface of revolution generated by revolving
   the circle in the xy-plane with radius {@code r2} and center
   {@code (r1,0,0)} around the y-axis. We are assuming that {@code r1 > r2}.
<p>
   Here are parametric equations for the circle in the xy-plane with
   radius {@code r2} and center {@code (r1,0,0)} and parameterized
   starting from the top, with parameter {@code 0 <= phi <= 2*PI}.
   <pre>{@code
      x(phi) = r1 + r2 * sin(phi)
      y(phi) =      r2 * cos(phi)
      z(phi) = 0
   }</pre>
   Here is the 3D rotation matrix that rotates around the y-axis
   by {@code theta} radians with {@code 0 <= theta <= 2*PI}.
   <pre>{@code
      [ cos(theta)   0   sin(theta)]
      [     0        1       0     ]
      [-sin(theta)   0   cos(theta)]
   }</pre>
   If we multiply the rotation matrix with the circle parameterization,
   we get a parameterization of the torus.
   <pre>{@code
      [ cos(theta)   0   sin(theta)]   [r1 + r2 * sin(phi)]
      [     0        1       0     ] * [     r2 * cos(phi)]
      [-sin(theta)   0   cos(theta)]   [        0         ]

      = ( r1*cos(theta) + r2*cos(theta)*sin(phi).
          r2*cos(phi),
         -r1*sin(theta) - r2*sin(theta)*sin(phi) )

      = ( (r1 + r2*sin(phi)) * cos(theta),
                r2*cos(phi),
         -(r1 + r2*sin(phi)) * sin(theta) )
   }</pre>
   See
     <a href="https://en.wikipedia.org/wiki/Torus#Geometry" target="_top">
              https://en.wikipedia.org/wiki/Torus#Geometry</a>

   @see TorusSector
*/
//@ts-check

import {Model, Vertex, LineSegment} from "../scene/SceneExport.js";
import {format} from "../scene/util/UtilExport.js";

export default class Torus extends Model
{
   r1;
   r2;
   n;
   k;

   /**
      Create a torus with a circle of revolution with radius {@code r1}
      and a cross section circle (circle of longitude) with radius
      {@code r2}.
   <p>
      The last two parameters determine the number of circles of
      longitude and the number of circles of latitude in the model.
   <p>
      If there are {@code n} circles of latitude, then each circle
      of longitude will have {@code n} line segments.
      If there are {@code k} circles of longitude, then each circle
      of latitude will have {@code k} line segments.
   <p>
      There must be at least three circles of longitude and at least
      three circles of latitude.

      @param {number} r1  radius of the circle of revolution
      @param {number} r2  radius of the cross section circle (circle of longitude)
      @param {number} n   number of circles of latitude
      @param {number} k   number of circles of longitude
   */
   constructor(r1 = .75, r2 = .25, n = 12, k = 16)
   {
      super(undefined, undefined, undefined, format("Torus(%.2f,%.2f,%d,%d)", r1, r2, n, k));

      if (n < 3)
         throw new Error("n must be greater than 2");
      if (k < 3)
         throw new Error("k must be greater than 2");

      this.r1 = r1;
      this.r2 = r2;
      this.n = n;
      this.k = k;

      // Create the torus's geometry.
      const deltaPhi   = (2 * Math.PI) / n;
      const deltaTheta = (2 * Math.PI) / k;

      // An array of vertices to be used to create line segments.
      /**@type {Vertex[][]} */
      const v = new Array(n);
      for (let x = 0; x < v.length; x += 1)
      {
         v[x] = new Array(k);
      }

      // Create all the vertices.
      for (let j = 0; j < k; ++j) // choose a rotation around the y-axis
      {
         const c1 = Math.cos(j * deltaTheta);
         const s1 = Math.sin(j * deltaTheta);

         for (let i = 0; i < n; ++i)  // go around a cross section circle
         {
            const c2 = Math.cos(i * deltaPhi);
            const s2 = Math.sin(i * deltaPhi);

            v[i][j] = new Vertex( (r1 + r2*s2) * c1,
                                        r2*c2,
                                 -(r1 + r2*s2) * s1 );
         }
      }

      // Add all of the vertices to this model.
      for (let i = 0; i < n; ++i)
      {
         for (let j = 0; j < k; ++j)
         {
            this.addVertex( v[i][j] );
         }
      }

      // Create the vertical cross-section circles.
      for (let j = 0; j < k; ++j) // choose a rotation around the y-axis
      {
         for (let i = 0; i < n - 1; ++i) // go around a cross section circle
         {
            this.addPrimitive(LineSegment.buildVertex( (i * k) + j, ((i+1) * k) + j ));
         }

         this.addPrimitive(LineSegment.buildVertex( ((n-1) * k) + j, (0 * k) + j ));
      }

      // Create all the horizontal circles around the torus.
      for (let i = 0; i < n; ++i) //choose a rotation around the cross section
      {
         for (let j = 0; j < k - 1; ++j) // go around a horizontal circle
         {
            this.addPrimitive(LineSegment.buildVertex( (i * k) + j, (i * k) + (j+1) ));
         }

         this.addPrimitive(LineSegment.buildVertex( (i * k) + (k-1), (i * k) + 0 ));
      }
   }
}//Torus
